# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mantra/resources/mantra_gui.ui'
#
# Created: Tue Jul 19 10:48:28 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(674, 597)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/webcam_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.widget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.title = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.title.setFont(font)
        self.title.setObjectName(_fromUtf8("title"))
        self.horizontalLayout.addWidget(self.title)
        self.label_8 = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/webcam_32.png")))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout.addWidget(self.label_8)
        self.verticalLayout.addWidget(self.widget)
        self.frame_6 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setMargin(4)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_9 = QtGui.QLabel(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setText(_fromUtf8(""))
        self.label_9.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/info.png")))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_2.addWidget(self.label_9)
        self.label_10 = QtGui.QLabel(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_2.addWidget(self.label_10)
        self.label_status = QtGui.QLabel(self.frame_6)
        self.label_status.setObjectName(_fromUtf8("label_status"))
        self.horizontalLayout_2.addWidget(self.label_status)
        self.verticalLayout.addWidget(self.frame_6)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setMargin(4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.frame_2)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.edit_file = QtGui.QLineEdit(self.groupBox)
        self.edit_file.setObjectName(_fromUtf8("edit_file"))
        self.gridLayout.addWidget(self.edit_file, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.button_browse = QtGui.QPushButton(self.groupBox)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/browse_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_browse.setIcon(icon1)
        self.button_browse.setObjectName(_fromUtf8("button_browse"))
        self.gridLayout.addWidget(self.button_browse, 0, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 2, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 3, 0, 1, 1)
        self.edit_resolution = QtGui.QLineEdit(self.groupBox)
        self.edit_resolution.setFrame(True)
        self.edit_resolution.setReadOnly(True)
        self.edit_resolution.setObjectName(_fromUtf8("edit_resolution"))
        self.gridLayout.addWidget(self.edit_resolution, 3, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 4, 0, 1, 1)
        self.spinbox_framerate = QtGui.QSpinBox(self.groupBox)
        self.spinbox_framerate.setObjectName(_fromUtf8("spinbox_framerate"))
        self.gridLayout.addWidget(self.spinbox_framerate, 4, 1, 1, 2)
        self.label_17 = QtGui.QLabel(self.groupBox)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 5, 0, 1, 1)
        self.combobox_comm_protocol = QtGui.QComboBox(self.groupBox)
        self.combobox_comm_protocol.setObjectName(_fromUtf8("combobox_comm_protocol"))
        self.combobox_comm_protocol.addItem(_fromUtf8(""))
        self.combobox_comm_protocol.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.combobox_comm_protocol, 5, 1, 1, 2)
        self.checkbox_log_samples = QtGui.QCheckBox(self.groupBox)
        self.checkbox_log_samples.setChecked(True)
        self.checkbox_log_samples.setObjectName(_fromUtf8("checkbox_log_samples"))
        self.gridLayout.addWidget(self.checkbox_log_samples, 6, 0, 1, 3)
        self.button_change_resolution = QtGui.QPushButton(self.groupBox)
        self.button_change_resolution.setIcon(icon)
        self.button_change_resolution.setObjectName(_fromUtf8("button_change_resolution"))
        self.gridLayout.addWidget(self.button_change_resolution, 3, 2, 1, 1)
        self.button_change_camera = QtGui.QPushButton(self.groupBox)
        self.button_change_camera.setIcon(icon)
        self.button_change_camera.setObjectName(_fromUtf8("button_change_camera"))
        self.gridLayout.addWidget(self.button_change_camera, 2, 2, 1, 1)
        self.edit_camera_dev = QtGui.QLineEdit(self.groupBox)
        self.edit_camera_dev.setReadOnly(True)
        self.edit_camera_dev.setObjectName(_fromUtf8("edit_camera_dev"))
        self.gridLayout.addWidget(self.edit_camera_dev, 2, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_5 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setStyleSheet(_fromUtf8(""))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_5.setMargin(4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.groupBox_5 = QtGui.QGroupBox(self.frame_5)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setVerticalSpacing(2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_objects = QtGui.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Sans Mono"))
        self.label_objects.setFont(font)
        self.label_objects.setTextFormat(QtCore.Qt.RichText)
        self.label_objects.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_objects.setObjectName(_fromUtf8("label_objects"))
        self.gridLayout_6.addWidget(self.label_objects, 0, 0, 1, 2)
        self.gridLayout_5.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 674, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuTracking = QtGui.QMenu(self.menuBar)
        self.menuTracking.setObjectName(_fromUtf8("menuTracking"))
        self.menuObjects = QtGui.QMenu(self.menuBar)
        self.menuObjects.setObjectName(_fromUtf8("menuObjects"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuView = QtGui.QMenu(self.menuBar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dock_camera_options = QtGui.QDockWidget(MainWindow)
        self.dock_camera_options.setMinimumSize(QtCore.QSize(350, 200))
        self.dock_camera_options.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dock_camera_options.setObjectName(_fromUtf8("dock_camera_options"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.layout_dock_camera_options = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.layout_dock_camera_options.setSpacing(0)
        self.layout_dock_camera_options.setMargin(4)
        self.layout_dock_camera_options.setObjectName(_fromUtf8("layout_dock_camera_options"))
        self.scrollarea_camera_options = QtGui.QScrollArea(self.dockWidgetContents_2)
        self.scrollarea_camera_options.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollarea_camera_options.setWidgetResizable(True)
        self.scrollarea_camera_options.setObjectName(_fromUtf8("scrollarea_camera_options"))
        self.scrollarea_camera_contents = QtGui.QWidget()
        self.scrollarea_camera_contents.setGeometry(QtCore.QRect(0, 0, 327, 204))
        self.scrollarea_camera_contents.setObjectName(_fromUtf8("scrollarea_camera_contents"))
        self.layout_camera_options = QtGui.QVBoxLayout(self.scrollarea_camera_contents)
        self.layout_camera_options.setSpacing(0)
        self.layout_camera_options.setMargin(0)
        self.layout_camera_options.setObjectName(_fromUtf8("layout_camera_options"))
        self.scrollarea_camera_options.setWidget(self.scrollarea_camera_contents)
        self.layout_dock_camera_options.addWidget(self.scrollarea_camera_options)
        self.dock_camera_options.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dock_camera_options)
        self.dock_advanced_options = QtGui.QDockWidget(MainWindow)
        self.dock_advanced_options.setMinimumSize(QtCore.QSize(350, 241))
        self.dock_advanced_options.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dock_advanced_options.setObjectName(_fromUtf8("dock_advanced_options"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setMargin(4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.toolbox_advanced_options = QtGui.QToolBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolbox_advanced_options.sizePolicy().hasHeightForWidth())
        self.toolbox_advanced_options.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.toolbox_advanced_options.setFont(font)
        self.toolbox_advanced_options.setObjectName(_fromUtf8("toolbox_advanced_options"))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 342, 138))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_6 = QtGui.QLabel(self.page_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.spinbox_smov_threshold = QtGui.QSpinBox(self.page_2)
        self.spinbox_smov_threshold.setMaximum(10000)
        self.spinbox_smov_threshold.setObjectName(_fromUtf8("spinbox_smov_threshold"))
        self.gridLayout_3.addWidget(self.spinbox_smov_threshold, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.page_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.spinbox_emov_threshold = QtGui.QSpinBox(self.page_2)
        self.spinbox_emov_threshold.setMaximum(10000)
        self.spinbox_emov_threshold.setObjectName(_fromUtf8("spinbox_emov_threshold"))
        self.gridLayout_3.addWidget(self.spinbox_emov_threshold, 1, 1, 1, 1)
        self.checkbox_v3d = QtGui.QCheckBox(self.page_2)
        self.checkbox_v3d.setObjectName(_fromUtf8("checkbox_v3d"))
        self.gridLayout_3.addWidget(self.checkbox_v3d, 2, 0, 1, 2)
        self.widget_2 = QtGui.QWidget(self.page_2)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.gridLayout_3.addWidget(self.widget_2, 3, 0, 1, 1)
        self.toolbox_advanced_options.addItem(self.page_2, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 342, 138))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.checkbox_monitor_tracking = QtGui.QCheckBox(self.page_3)
        self.checkbox_monitor_tracking.setChecked(True)
        self.checkbox_monitor_tracking.setObjectName(_fromUtf8("checkbox_monitor_tracking"))
        self.verticalLayout_9.addWidget(self.checkbox_monitor_tracking)
        self.checkbox_monitor_webcam = QtGui.QCheckBox(self.page_3)
        self.checkbox_monitor_webcam.setObjectName(_fromUtf8("checkbox_monitor_webcam"))
        self.verticalLayout_9.addWidget(self.checkbox_monitor_webcam)
        self.widget_3 = QtGui.QWidget(self.page_3)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.verticalLayout_9.addWidget(self.widget_3)
        self.toolbox_advanced_options.addItem(self.page_3, _fromUtf8(""))
        self.page_5 = QtGui.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 342, 138))
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.gridLayout_4 = QtGui.QGridLayout(self.page_5)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_12 = QtGui.QLabel(self.page_5)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_4.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.page_5)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_4.addWidget(self.label_13, 3, 0, 1, 1)
        self.edit_host = QtGui.QLineEdit(self.page_5)
        self.edit_host.setObjectName(_fromUtf8("edit_host"))
        self.gridLayout_4.addWidget(self.edit_host, 1, 1, 1, 1)
        self.spinbox_port = QtGui.QSpinBox(self.page_5)
        self.spinbox_port.setMaximum(100000)
        self.spinbox_port.setObjectName(_fromUtf8("spinbox_port"))
        self.gridLayout_4.addWidget(self.spinbox_port, 3, 1, 1, 1)
        self.widget_4 = QtGui.QWidget(self.page_5)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.gridLayout_4.addWidget(self.widget_4, 4, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.page_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setTextFormat(QtCore.Qt.PlainText)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_4.addWidget(self.label_14, 0, 0, 1, 2)
        self.toolbox_advanced_options.addItem(self.page_5, _fromUtf8(""))
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 358, 147))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.gridLayout_2 = QtGui.QGridLayout(self.page_4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_2 = QtGui.QLabel(self.page_4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.combobox_match_mode = QtGui.QComboBox(self.page_4)
        self.combobox_match_mode.setObjectName(_fromUtf8("combobox_match_mode"))
        self.combobox_match_mode.addItem(_fromUtf8(""))
        self.combobox_match_mode.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.combobox_match_mode, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.page_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.combobox_size_mode = QtGui.QComboBox(self.page_4)
        self.combobox_size_mode.setObjectName(_fromUtf8("combobox_size_mode"))
        self.combobox_size_mode.addItem(_fromUtf8(""))
        self.combobox_size_mode.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.combobox_size_mode, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.page_4)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.spinbox_min_z = QtGui.QSpinBox(self.page_4)
        self.spinbox_min_z.setMaximum(10000)
        self.spinbox_min_z.setObjectName(_fromUtf8("spinbox_min_z"))
        self.gridLayout_2.addWidget(self.spinbox_min_z, 2, 1, 1, 1)
        self.checkbox_control_mouse = QtGui.QCheckBox(self.page_4)
        self.checkbox_control_mouse.setObjectName(_fromUtf8("checkbox_control_mouse"))
        self.gridLayout_2.addWidget(self.checkbox_control_mouse, 3, 0, 1, 2)
        self.widget_5 = QtGui.QWidget(self.page_4)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.gridLayout_2.addWidget(self.widget_5, 4, 0, 1, 1)
        self.toolbox_advanced_options.addItem(self.page_4, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.toolbox_advanced_options)
        self.dock_advanced_options.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dock_advanced_options)
        self.actionQuit = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/quit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon2)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionStart = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/record.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStart.setIcon(icon3)
        self.actionStart.setObjectName(_fromUtf8("actionStart"))
        self.actionStop = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/stop_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon4)
        self.actionStop.setObjectName(_fromUtf8("actionStop"))
        self.actionPause = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/pause_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPause.setIcon(icon5)
        self.actionPause.setObjectName(_fromUtf8("actionPause"))
        self.actionAdd_object = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/add_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_object.setIcon(icon6)
        self.actionAdd_object.setObjectName(_fromUtf8("actionAdd_object"))
        self.actionClear_objects = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/clear_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClear_objects.setIcon(icon7)
        self.actionClear_objects.setObjectName(_fromUtf8("actionClear_objects"))
        self.actionAbout = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/info.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon8)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionShow_advanced_options = QtGui.QAction(MainWindow)
        self.actionShow_advanced_options.setCheckable(True)
        self.actionShow_advanced_options.setObjectName(_fromUtf8("actionShow_advanced_options"))
        self.actionShow_camera_options = QtGui.QAction(MainWindow)
        self.actionShow_camera_options.setCheckable(True)
        self.actionShow_camera_options.setObjectName(_fromUtf8("actionShow_camera_options"))
        self.actionSave_profile = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/save_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_profile.setIcon(icon9)
        self.actionSave_profile.setObjectName(_fromUtf8("actionSave_profile"))
        self.actionOpen_profile = QtGui.QAction(MainWindow)
        self.actionOpen_profile.setIcon(icon1)
        self.actionOpen_profile.setObjectName(_fromUtf8("actionOpen_profile"))
        self.menuFile.addAction(self.actionSave_profile)
        self.menuFile.addAction(self.actionOpen_profile)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuTracking.addAction(self.actionStart)
        self.menuTracking.addAction(self.actionStop)
        self.menuTracking.addAction(self.actionPause)
        self.menuObjects.addAction(self.actionAdd_object)
        self.menuObjects.addAction(self.actionClear_objects)
        self.menuHelp.addAction(self.actionAbout)
        self.menuView.addAction(self.actionShow_camera_options)
        self.menuView.addAction(self.actionShow_advanced_options)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuTracking.menuAction())
        self.menuBar.addAction(self.menuObjects.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionStart)
        self.toolBar.addAction(self.actionStop)
        self.toolBar.addAction(self.actionPause)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAdd_object)
        self.toolBar.addAction(self.actionClear_objects)

        self.retranslateUi(MainWindow)
        self.toolbox_advanced_options.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MANTRA 0.3", None, QtGui.QApplication.UnicodeUTF8))
        self.title.setStyleSheet(QtGui.QApplication.translate("MainWindow", "color:#3465a4;", None, QtGui.QApplication.UnicodeUTF8))
        self.title.setText(QtGui.QApplication.translate("MainWindow", "MANTRA [version]", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_6.setStyleSheet(QtGui.QApplication.translate("MainWindow", "background-color: #2e3436;\n"
"color: #eeeeec;", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_status.setText(QtGui.QApplication.translate("MainWindow", "idle", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Tracking and recording", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_file.setText(QtGui.QApplication.translate("MainWindow", "recording.tsv", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Data file", None, QtGui.QApplication.UnicodeUTF8))
        self.button_browse.setText(QtGui.QApplication.translate("MainWindow", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Camera device", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Framerate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Network protocol", None, QtGui.QApplication.UnicodeUTF8))
        self.combobox_comm_protocol.setItemText(0, QtGui.QApplication.translate("MainWindow", "TCP (For E-prime)", None, QtGui.QApplication.UnicodeUTF8))
        self.combobox_comm_protocol.setItemText(1, QtGui.QApplication.translate("MainWindow", "UDP (For Python)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkbox_log_samples.setText(QtGui.QApplication.translate("MainWindow", "Log samples", None, QtGui.QApplication.UnicodeUTF8))
        self.button_change_resolution.setText(QtGui.QApplication.translate("MainWindow", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.button_change_camera.setText(QtGui.QApplication.translate("MainWindow", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "Objects", None, QtGui.QApplication.UnicodeUTF8))
        self.label_objects.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">No objects have been defined</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTracking.setTitle(QtGui.QApplication.translate("MainWindow", "Tracking", None, QtGui.QApplication.UnicodeUTF8))
        self.menuObjects.setTitle(QtGui.QApplication.translate("MainWindow", "Objects", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.dock_camera_options.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Camera options", None, QtGui.QApplication.UnicodeUTF8))
        self.dock_advanced_options.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Advanced options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Movement start velocity threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Movement end velocity threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.checkbox_v3d.setText(QtGui.QApplication.translate("MainWindow", "Use Z-coordinate (depth) to estimate velocity", None, QtGui.QApplication.UnicodeUTF8))
        self.toolbox_advanced_options.setItemText(self.toolbox_advanced_options.indexOf(self.page_2), QtGui.QApplication.translate("MainWindow", "Velocity and movement", None, QtGui.QApplication.UnicodeUTF8))
        self.checkbox_monitor_tracking.setText(QtGui.QApplication.translate("MainWindow", "Monitor tracking", None, QtGui.QApplication.UnicodeUTF8))
        self.checkbox_monitor_webcam.setText(QtGui.QApplication.translate("MainWindow", "Show webcam output", None, QtGui.QApplication.UnicodeUTF8))
        self.toolbox_advanced_options.setItemText(self.toolbox_advanced_options.indexOf(self.page_3), QtGui.QApplication.translate("MainWindow", "Monitor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Listening to host (empty = all)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Listening on port", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Note: changing the network settings only has an effect before tracking is started for the first time.", None, QtGui.QApplication.UnicodeUTF8))
        self.toolbox_advanced_options.setItemText(self.toolbox_advanced_options.indexOf(self.page_5), QtGui.QApplication.translate("MainWindow", "Networking", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Color match mode", None, QtGui.QApplication.UnicodeUTF8))
        self.combobox_match_mode.setItemText(0, QtGui.QApplication.translate("MainWindow", "Absolute (no color constancy)", None, QtGui.QApplication.UnicodeUTF8))
        self.combobox_match_mode.setItemText(1, QtGui.QApplication.translate("MainWindow", "Relative (some color constancy)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Depth estimation mode", None, QtGui.QApplication.UnicodeUTF8))
        self.combobox_size_mode.setItemText(0, QtGui.QApplication.translate("MainWindow", "Surface (count pixels)", None, QtGui.QApplication.UnicodeUTF8))
        self.combobox_size_mode.setItemText(1, QtGui.QApplication.translate("MainWindow", "Width and height", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Minimum pixelcount", None, QtGui.QApplication.UnicodeUTF8))
        self.checkbox_control_mouse.setText(QtGui.QApplication.translate("MainWindow", "Use tracking to control mouse cursor", None, QtGui.QApplication.UnicodeUTF8))
        self.toolbox_advanced_options.setItemText(self.toolbox_advanced_options.indexOf(self.page_4), QtGui.QApplication.translate("MainWindow", "Other options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPause.setText(QtGui.QApplication.translate("MainWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_object.setText(QtGui.QApplication.translate("MainWindow", "Add object", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_objects.setText(QtGui.QApplication.translate("MainWindow", "Clear objects", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_advanced_options.setText(QtGui.QApplication.translate("MainWindow", "Show advanced options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_camera_options.setText(QtGui.QApplication.translate("MainWindow", "Show camera options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_profile.setText(QtGui.QApplication.translate("MainWindow", "Save profile", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_profile.setText(QtGui.QApplication.translate("MainWindow", "Open profile", None, QtGui.QApplication.UnicodeUTF8))

import mantra_rc
